[ServerMap]
  [ServerMap.Gemini]
    Port = ":1965"
    Timeout = 5

[TLS]
  CertFile = "test/MyCertificate.crt"
  KeyFile = "test/MyKey.key"

[Log]
  Level = "info"
  ToStd = true # 目前并不起作用
  LogRotate = true
  Development = false
  Sampling = true # todo: can be config some day
  [Log.Rotate]
    Filename = ["log", "test"]
    MaxSize = 100 # 单个日志最大大小
    MaxAge = 30 # 最大存活日期
    MaxBackups = 30 # 最大日志数量

[Gemini]
  [[Gemini.File]]
    Router = "/file"
    Path = "test.gemini"

  [[Gemini.Dir]]
    Router = "/dir"
    Path = "test/dir"
    Index = "index.gmi"
    AutoCatalogue = false

  [[Gemini.Proxy]]
    Router = "/url"
    Method = "GET"
    URL = "http://127.0.0.1:12222"
    MetaField = "meta"
    BodyField = "body"